import type { LucideIcon } from "lucide-react";
import {
  Apple,
  Briefcase,
  Building2,
  Church,
  ConciergeBell,
  Dumbbell,
  FileText,
  GraduationCap,
  Hammer,
  Heart,
  Leaf,
  Monitor,
  Palette,
  ShoppingCart,
  Stethoscope,
  Truck,
  TrendingUp,
  Users,
} from "lucide-react";

export const categoryIcons: Record<string, LucideIcon> = {
  "Administratif et juridique": FileText,
  Agroalimentaire: Apple,
  "Arts graphiques et création artistique": Palette,
  "Bien-être et beauté": Heart,
  "Communication et médias": TrendingUp,
  Construction: Building2,
  "Formation initiale et continue": GraduationCap,
  Informatique: Monitor,
  "Marketing et commerce": ShoppingCart,
  "Meubles, textiles, et autres activités de manufacture": Hammer,
  "RSE-QVT": Leaf,
  "Santé et social": Stethoscope,
  "Services à la personne": Users,
  Services: ConciergeBell,
  "Services aux entreprises": Briefcase,
  Spiritualité: Church,
  "Sports, loisirs et divertissements": Dumbbell,
  Transports: Truck,
};
